import { type Metadata } from 'next'
import './globals.css'
import ThemeProvider from '@/providers/ThemeProvider';
import SettingProvider from '@/providers/SettingProvider';
import SidebarProvider from '@/providers/SidebarProvider';

export const metadata: Metadata = {
  title: 'HCMUT - App',
  description: 'Generated by create next app',
  applicationName: 'HCMUT - App',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'nhatdev',
  authors: [{ name: 'nhatdev' }],
  creator: 'nhatdev'
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SettingProvider>
          <ThemeProvider>
            <SidebarProvider>
              {children}
            </SidebarProvider>
          </ThemeProvider>
        </SettingProvider>
      </body>
    </html>
  )
}
