import { type Metadata } from 'next'
import './globals.css'
import LayoutStructure from './layoutWrapper'

export const metadata: Metadata = {
  title: 'HCMUT - App',
  description: 'Generated by create next app',
  applicationName: 'HCMUT - App',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'nhatdev',
  authors: [{ name: 'nhatdev' }],
  creator: 'nhatdev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='max-h-dvh h-dvh'>
      <body className='max-h-dvh h-dvh'>
        <LayoutStructure>
          {children}
        </LayoutStructure>
      </body>
    </html>
  )
}
